name: Update Local Now IPTV

on:
  push:
    branches:
      - main

jobs:
  update-iptv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure git for safe directory
        run: |
          git config --global --add safe.directory /home/runner/work/localnow/localnow

      - name: Clear core.sshCommand configurations
        run: |
          git config --local --name-only --get-regexp core.sshCommand && git config --local --unset-all core.sshCommand || true
          git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"

      - name: Unset GitHub extra headers
        run: |
          git config --local --name-only --get-regexp http.https://github.com/.extraheader && git config --local --unset-all http.https://github.com/.extraheader
          git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http.https://github.com/.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"

      - name: Your remaining steps
        run: |
          # Add your other steps here
